# Site
name: "Fabiola Faria"
title: "SEO & Data Analytics Expert"
description: "Fabiola Faria é Google Marketing Expert especialista em SEO, Google Analytics e Google Data Studio. Fique por dentro de Estratégias de Search Engine Marketing orientadas a Dados."
meta_description:
logo: "Fabiola Faria"
favicon: 'assets/images/favicon.png'
paginate: 12
baseurl:
url: "https://fabiolafaria.com.br"
email: 'fabiola@seoanalytics.com.br'
google_analytics: ''
disqus: 'seoanalytics'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  sal:
    name: Fabiola
    display_name: Fabi
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: fabiola@seoanalytics.com.br
    web: https://www.fabiolafaria.com.br
    twitter: https://twitter.com/fabiola_faria
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: Fabiola
    display_name: Fabi
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: fabiola@seoanalytics.com.br
    web: https://www.fabiolafaria.com.br
    twitter: https://twitter.com/fabiola_faria
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge